celo-org/celo-composer

packages/react-app/package.json
packages/react-app/yarn.lock

updates use-contractkit and contractkit to latest versions

upgrade use-contractkit out of beta

---

package.json
packages/hardhat/package.json
packages/react-app/package.json

configuring yarn workspaces

---

packages/hardhat/contracts/Storage.sol

modifier prevents the storage from being modified outside storage contract.

Added Modifier to Contract

---

packages/hardhat/contracts/Greeter.sol

Added an external modifier to ensure the code is only modifiable only outside the contract.

Added modifier

---

packages/react-app/components/GreeterContract.tsx
packages/react-app/components/StorageContract.tsx
packages/react-app/package.json
packages/react-app/pages/index.tsx

Changed @celo-progressive-dapp-starter/hardhat imports to absolute as monorepo packages should be configured

change imports from relative to absolute

---

packages/react-app/components/index.ts
packages/react-app/components/layout/AppLayout.tsx
packages/react-app/components/layout/Footer.tsx
packages/react-app/components/layout/Header.tsx
packages/react-app/components/meta/Meta.tsx
packages/react-app/pages/_app.tsx
packages/react-app/pages/index.tsx

- Create Header and Footer components 
- Create reusable Meta Component for the SEO (Will be useful when the app will have more than 1 page) 
- Create AppLayout component to easier organize and have a better view of the layout 
- Fix lint warnings/errors

Improve front end architecture

---

packages/react-app/pages/index.tsx

Automatically changes MUI theme to dark mode when the user has this preference enabled on their OS.

auto dark mode

---

packages/react-app/components/ThemeSwitcher.tsx
packages/react-app/components/layout/Header.tsx
packages/react-app/contexts/UserTheme.tsx
packages/react-app/pages/_app.tsx
packages/react-app/pages/index.tsx

**Add possibility to switch between light and dark mode**
- Create a custom theme context (to be able to switch the theme from anywhere in the application)
- Use the material UI theme provider
- Create a beautiful switch component
- By default we use the user theme based on the preference on their OS. 
https://user-images.githubusercontent.com/34569321/160451569-39abdf99-bd41-49d8-9846-f585098148c4.mov

add switch to change dark/light mode

---

packages/hardhat/contracts/Oracle.sol
packages/hardhat/package.json
packages/hardhat/test/oracle-test.js
yarn.lock

- Added `Oracle.sol` contract
- Added `oracle-test.js` test
- Fixed the `test` command in `package.json`

Adding RedStone oracles example

---

packages/react-app/components/AccountInfo.tsx
packages/react-app/components/index.ts
packages/react-app/components/layout/Header.tsx
packages/react-app/package.json
packages/react-app/pages/index.tsx
yarn.lock

Added functionality to show users balance in DApp. I think this may be handy in some cases

show actual CELO balance

---

packages/react-app/components/AccountInfo.tsx

fix swapped cEUR and cUSD values

---

packages/react-app/components/StorageContract.tsx
packages/react-app/package.json
packages/react-app/utils/index.ts
yarn.lock

Added table to display data fetched from the graph

Visualize graph output

---

packages/flutter-app/pubspec.lock
packages/flutter-app/pubspec.yaml

flutter_walletconnect added from pub.dev

---

packages/hardhat/README.md
packages/hardhat/hardhat.config.js

Figment DataHub support added and Readme updated

---

packages/hardhat/hardhat.config.js
packages/react-app/components/AccountInfo.tsx

Clear error validateDOMNesting(...): <div> cannot appear as a descendant of <p> and made changes to Celo network account config in hardhat to accept array and not string

Fix error : validateDOMNesting(...): <div> cannot appear as a descendant of <p>

---

packages/flutter-app/README.md
packages/flutter-app/lib/extensions/index.dart
packages/flutter-app/lib/extensions/screen.dart
packages/flutter-app/lib/main.dart
packages/flutter-app/lib/screens/home_screen.dart
packages/flutter-app/lib/screens/index.dart
packages/flutter-app/lib/screens/splash_screen.dart
packages/flutter-app/lib/utils/constants.dart
packages/flutter-app/lib/utils/index.dart
packages/flutter-app/lib/utils/route.dart
packages/flutter-app/lib/utils/string_constant.dart
packages/flutter-app/lib/utils/theme_config.dart
packages/flutter-app/lib/utils/toast.dart
packages/flutter-app/lib/widgets/custom_textfield.dart
packages/flutter-app/lib/widgets/custom_toggle.dart
packages/flutter-app/lib/widgets/index.dart
packages/flutter-app/lib/widgets/primary_button.dart
packages/flutter-app/lib/widgets/receive_card.dart
packages/flutter-app/lib/widgets/spacer.dart
packages/flutter-app/macos/Podfile.lock
packages/flutter-app/macos/Runner.xcodeproj/project.pbxproj
packages/flutter-app/macos/Runner.xcworkspace/contents.xcworkspacedata
packages/flutter-app/pubspec.yaml

Improve App UI.
Restructure files.
Added toggle to switch between dark mode and light mode.
Added receive button on click to show a modal where users can scan QR code or copy their wallet address.
Added splash screen.
Separate constant texts from widgets.

Improve flutter app ui with some fixes

---

packages/flutter-app/README.md
packages/flutter-app/android/app/src/main/AndroidManifest.xml
packages/flutter-app/assets/lang/en-US.json
packages/flutter-app/assets/lang/fr-FR.json
packages/flutter-app/lib/contracts/stream_chicken_2.abi.json
packages/flutter-app/lib/contracts/stream_chicken_2.g.dart
packages/flutter-app/lib/controllers/wallet_controller.dart
packages/flutter-app/lib/main.dart
packages/flutter-app/lib/model/app_info.dart
packages/flutter-app/lib/model/crypto_wallet.dart
packages/flutter-app/lib/model/language.dart
packages/flutter-app/lib/screens/home/index.dart
packages/flutter-app/lib/screens/home/setting.dart
packages/flutter-app/lib/screens/home_screen.dart
packages/flutter-app/lib/utils/constants.dart
packages/flutter-app/lib/utils/deeplink.dart
packages/flutter-app/lib/utils/helper.dart
packages/flutter-app/lib/utils/string_constant.dart
packages/flutter-app/lib/utils/wallet_connect_ethereum_credentials.dart
packages/flutter-app/macos/Flutter/GeneratedPluginRegistrant.swift
packages/flutter-app/pubspec.yaml

Added localization support
Fixed wallet connect with trustwallet (Mainnet)
Update README.md for some changes
Note: Currently wallet connect is not working with Valora app but will try to figure out what might wrong

Added localization support and fixed wallet connet with trustwallet

---

packages/hardhat/contracts/SimpleERC115.sol
packages/hardhat/contracts/SimpleERC777.sol
packages/hardhat/contracts/SimpleProxyContract.sol
packages/hardhat/contracts/SimpleVestingWallet.sol

Added example for vesting wallet, erc777, erc1155 examples

---

packages/react-app/package.json
packages/react-app/pages/index.tsx

link to https://github.com/celo-org/celo-composer/issues/140

fix wrong react/app package and wrong contract address

---

packages/react-app-tailwindcss/package.json

adds support for `useContractReads`. ( multicall )  out of the box

upgrade celo rainbowkit config

---

packages/react-native-app/app.json

fix: `android-manifest.plugin.js` resolve bug

---

bin/create.js
package.json
packages/react-app/components/HeaderRC.tsx
packages/react-app/package.json
packages/react-app/pages/_app.tsx
packages/react-app/yarn.lock

Updates:
- Updating versions of the react-app package.
- Solving Typescript bug related to wagmi versioning.
- Solving bug on CLI script about renaming and moving files depending on the web3 front-end library selection.
- CSS update on react-celo header file of the react-app package.

Fixing minor bugs

---

bin/create.js
bin/index.js
package.json
packages/hardhat/yarn.lock
packages/react-app/components/Header.tsx
packages/react-native-app-without-expo/yarn.lock
packages/react-native-app/yarn.lock

fix: useEffect slowing down MiniPay Site Tester

---

packages/react-app/package.json

fix: update `wagmi` & `@celo/rainbowkit-celo`

---

README.md
packages/hardhat/README.md
packages/react-app/README.md

290 feature update hardhat commands

---

README.md
packages/hardhat/README.md
packages/hardhat/package.json
packages/react-app/README.md

- add instructions for deployment and links to detailed guides
- remove duplicated instructions
Closes #314

add missing instructions to main README
